# Generated by Django 5.2.8 on 2025-12-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
