# Generated by Django 5.2.8 on 2025-12-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_booking_order_id_booking_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sequence_number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
